name: Terraform Init

on:
  workflow_dispatch:
  push:
    branches: [ main ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
  TF_VAR_DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
  TF_VAR_PRIVATE_KEY_PATH: ${{ secrets.SSH_PRIVATE_KEY }}
  TF_VAR_SSH_KEY_ID: ${{ secrets.SSH_KEY_ID }}

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Verificar Docker
      - name: Check Docker
        run: |
          if ! command -v docker &> /dev/null; then
            exit 1
          fi
          docker --version

      # 3. Cache para Docker Buildx
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 5. Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          sudo apt-get update || (sleep 10 && sudo apt-get update)
          sudo apt-get install -y unzip

      # 6. Configurar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.8  # Asegúrate de usar una versión compatible

      # 7. Configurar SSH key
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/serverxweb
          chmod 600 ~/.ssh/serverxweb

      # 8. Inicializar Terraform
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          TF_VAR_DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          terraform init \
            -backend=true \
            -backend-config="access_key=${{ secrets.SPACES_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.SPACES_SECRET_KEY }}" \
            -force-copy

      # 9. Terraform Plan
      - name: Terraform Plan
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          terraform plan

      # 10. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

      # 11. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 12. Construir y publicar imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      # 13. Desplegar la aplicación en el Droplet
      - name: Deploy application
        run: |
          ssh -i ~/.ssh/serverxweb root@$(terraform output -raw droplet_ip) 'cd /var/www/app && git pull && pm2 restart all'

      # 14. Notificaciones de éxito y fallo
      - name: Notify on success
        if: success()
        run: echo "Deployment successful!"

      - name: Notify on failure
        if: failure()
        run: echo "Deployment failed."

      # 15. Limpieza de cache
      - name: Move cache
        run: |
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache